services:
  - type: web
    name: vanigan-whatsapp-bot
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: WHATSAPP_VERIFY_TOKEN
        sync: false
      - key: WHATSAPP_API_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_NUMBER_ID
        value: 1091986343995328
      - key: WHATSAPP_APP_ID
        sync: false
      - key: FRONTEND_URL
        value: https://vanigan-whats-app.vercel.app/
